---
title: 'Scaling Models Series #1. NOMINATE: Multi-Dimensional Scaling of Roll-Call Voting in R'
author: "Daniel Braby"
date: "25/06/2021"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Scaling Models in Political Science

Yesterday I posted a draft of a book chapter by myself, Benjamin Guinaudeau and Marius Saltzer, titled 'Scaling Models in Political Science'.

After fielding the idea on Twitter, I've decided to cover a workflow for implementing the procedures we cover in the chapter using the R Programming Language.

I will go into a little bit more depth regarding the method and their applications, but for the most part this will cover implementing these procedures for yourself.

### A brief note on learning with coding examples

Some call now the 'golden age of data science'. Those people may be speaking too soon. But I think one key takeaway of the moment is the focus on open science and reproducible research. This, at least, has encouraged a shift away from point-and-click statistical analysis programmes and a move towards scripting data wrangling and analysis procedures.

So far as my own education on this area. In undergraduate I was taught quantitative methods in SPSS. Then in my Masters year I learned quantitative methods in R with the excellent Kosuke Imai's 'Quantitative Social Science' as a coursebook.

I realised that in learning statistical procedures in SPSS, I learned doing, but i did not know what. R is a powerful tool to jointly learn statistical methods and coding. Two key advantges of R to this end are the ability to execute scripts and functions line-by-line, we gain insight we see just whats going on under the hood, and it has a spirited community who have developed packages with code for easily conducting your own analysis.


## Learning and Teaching Scaling Models

So why write this? All the material on learning how these methods work, what kind of data we use, how we handle it and how to implement it is out there. But, it is, as far as I know, contained across multiple documents. Thus, one neat document that outlines the whole process is useful for getting people to a position where they are comfortable with the whole process.

A nice, readable introduction to these things, for my preference, should contain a minimal outline of whats going on, programming examples, data (and how to get it) and perhaps some more detailed exposition.


## Part 1- Roll-Call Voting

A roll-call vote is simply a vote in which a legislators vote on a bill is recorded as "yea" or "nay" as their name is called by a clerk or deputy. Given we have a known record of how each (present) legislator has voted we generate binary choice data for each vote.

In many Parliaments around the World, roll-call votes are conducted, but they are not essential for a vote to be held in the legislature. For instance, in the US senate, under the Constitution, a roll-call vote is only conducted if demanded by one-fifth of Senators present. 

Given that we have records of legislative voting via roll-calls or in some settings by signed ballots which are later published, legislatures generate binary political choice data by voting.



## NOMINATE: The Gears in the Engine

NOMINATE (a very clever acronym for Nominal Three Step Estimation) is a multidimensional scaling algorithm developed by Keith T. Poole and Howard Rosenthal (1985). The algorithm has been few multiple iterations, which I will cover in this post, but let us first lay bare the consistent components of these modelling techniques.

All NOMINATE scaling procedures operate under the same fundamental assumptions, allowing us to positively assess the ideological position of legislators.

Assumption #1- alternative choices, in this case the aggregation of votes as "yea" or "nay" given a bill, can be projected to a low-dimensional Euclidean Space.

Assumption #2- embedded in those low dimensional representations, individuals assume normally distributed utility functions

Assumption #3 (2 and a half, really)- given utility functions are normally distributed, they maximise at their ideal points.

Ideal points are interpreted as being individuals' most preferred outcome, hence, position.


